export const characters = [
  {
    "name": "Maria",
    "image": "Mary.png",
    "hints": [
      "Uma profecia disse que uma longa espada me atravessaria.",
      "Meu esposo aceitou um grande desafio por causa de um sonho.",
      "Ofereci um par de rolas ou dois pombos novos quando fui ao templo.",
      "Fiquei por três dias sem saber onde meu filho estava.",
      "Recebi uma visita inesperada que mudou minha vida para sempre.",
      "Fugi para outro país para proteger meu filho de um rei cruel.",
      "Tive um filho apesar de virgem.",
      "Meu marido era carpinteiro e ensinou essa profissão a meu filho.",
      "Sou lembrada como a mãe do homem mais importante da história."
    ]
  },
  {
    name: "Pedro",
    image: "Pedro.jpg",
    hints: [
      "Fiz uma promessa, porém não a cumpri.",
      "Tive uma visão que mudou minha vida.",
      "Paguei um imposto com uma moeda que ganhei por milagre.",
      "Fui repreendido publicamente por um amigo meu.",
      "Fui libertado da prisão por um anjo enquanto os irmãos oravam por mim.",
      "Milagrosamente minha sombra curava pessoas.",
      "Neguei a Jesus três vezes.",
      "Cortei a orelha de um soldado.",
      "Andei sobre as águas com Jesus.",
    ],
  },

{
    name: "José do Egito",
    image: "Joseph.jpg",
    hints: [
      "Um dos meus nomes era Zafenate-Paneia.",
      "Sonhei que a Lua e o Sol se curvavam perante uma estrela.",
      "Fiquei preso com o chefe dos padeiros e o chefe dos copeiros.",
      "Dei um conselho ao faraó que salvou o Egito da fome.",
      "Deus transformou o mal que sofri em algo bom.",
      "Ganhei uma túnica colorida de presente do meu pai.",
      "Fui vendido como escravo por meus próprios irmãos.",
      "Cheguei a ser o segundo homem mais poderoso do Egito.",
      "Fui acusado injustamente e lançado na prisão.",
    ],
  },

{
    name: "Miriã",
    image: "Miriam.jpg",
    hints: [
      "Meu nome junto com os dos meus irmãos é mencionado no livro de Miqueias.",
      "Sou a primeira mulher chamada de profetisa na Bíblia.",
      "Sou filha de Anrão e Joquebede.",
      "Liderei as mulheres em um cântico após um grande livramento.",
      "Fui castigada com lepra por ter sido rebelde, mas fui perdoada.",
      "Cantei e toquei tamborins após a travessia do mar Vermelho.",
      "Ajudei a salvar meu irmão quando ele era um bebê.",
      "Minha família liderou a saída do povo do Egito.",
      "Sou irmã de Moisés e Arão.",
    ],
  },

  {
    "name": "Samuel",
    "image": "Samuel.jpg",
    "hints": [
      "Minha mãe cantou um cântico que mais tarde se refletiria em outra história famosa.",
      "Meus dois filhos me trouxeram muita tristeza.",
      "Fui o último da minha função antes de um novo sistema de governo.",
      "Exortei um rei quando ele poupou o que deveria destruir.",
      "Untei com óleo dois homens que se tornaram reis.",
      "Uma voz misteriosa me chamou durante a noite, mas eu não sabia quem era.",
      "Fui um profeta e um nazireu.",
      "Minha mãe fez um voto antes mesmo de eu nascer.",
      "Fui um dos maiores juízes e profetas de Israel."
    ]
  },
  {
    "name": "Noemi",
    "image": "Noemi.jpg",
    "hints": [
      "Meu nome significa algo, mas cheguei a rejeitá-lo por um tempo.",
      "Minha decisão impactou a linhagem do maior rei de Israel.",
      "Fui acompanhada por alguém que fez um voto muito famoso.",
      "Passei um período vivendo em uma terra estrangeira.",
      "Ajudei a planejar um encontro decisivo para minha família.",
      "Fui restaurada quando um parente redentor apareceu.",
      "Minha história está registrada em um dos livros mais curtos da Bíblia.",
      "Uma grande tragédia me fez mudar de país.",
      "Sou lembrada como sogra de uma mulher fiel e admirável."
    ]
  },
  {
    "name": "Saul",
    "image": "Saul.jpg",
    "author": "Kauã Bernardo",
    "hints": [
      "Eu fiz uma coisa que embora fosse para Jeová não cabia a mim fazer.",
      "Meu tio se chamava Abner.",
      "Minha esposa se chamava Ainoã",
      "No principio eu era modesto.",
      "No fim me tornei invejoso",
      "Procurei uma vidente ",
      "Tentei cravar um homem na parede",
      "Meu filho se tornou o melhor amigo do meu inimigo.",
      "Eu ouvia música para acalmar pensamentos ruins."
    ]
  },
  {
    "name": "Sansão",
    "image": "Samson.jpg",
    "hints": [
      "Fui obrigado a seguir regras específicas desde antes do meu nascimento.",
      "Contei um enigma sobre algo doce vindo de algo forte.",
      "Capturei 300 raposas e fiz um incêndio em um campo com elas.",
      "Fui traído por alguém que dizia me amar.",
      "Fui cegado pelos meus inimigos.",
      "Matei 1000 homens com uma arma nada convencional.",
      "Derrotei um grande número de inimigos em um ato final.",
      "Minha força não vinha de mim, mas de um voto especial.",
      "Meu nome é lembrado entre os juízes de Israel."
    ]
  },
  {
    "name": "Ezequias",
    "image": "",
    "hints": [
      "Fui aconselhado pelo profeta Isaías.",
      "Mandei destruir a serpente de cobre que Moisés tinha feito.",
      "Fui responsável pela construção de umg rande aqueduto.",
      "Fui imprudente ao mostrar as riquezas do reino aos mensageiros de Babilônia.",
      "Recebi uma mensagem dura sobre minha saúde, mas ela foi revertida.",
      "Vi um grande exército ser derrotado sem precisar lutar.",
      "Fui elogiado como um dos melhores reis de Judá.",
      "Destruí altares idólatras para restaurar a adoração verdadeira.",
      "Meu inimigo foi Senaqueribe, filho de Sargão II."
    ]
  },
  
  {
    name: "Moisés",
    image: "https://i.pinimg.com/736x/41/7b/53/417b53f0d8a76b2cf5974970b56d5ad7.jpg",
    hints: [
      "Um estrangeiro me deu um novo lar e um novo nome de família",
      "Uma parte do meu corpo precisava ser sustentada por outros para garantir uma vitória",
      "Minha morte foi supervisionada, mas nunca testemunhada por outro humano",
      "Minha esposa se chamava Zípora",
      "Meu irmão se chamava Arão.",
      "Golpeei uma rocha para dela sair água.",
      "Fui escolhido por Deus para libertar os israelitas do Egito.",
      "Abri o Mar Vermelho com a ajuda de Jeová.",
      "Recebi os Dez Mandamentos.",
    ],
  },
  {
    name: "Davi",
    image: "David.jpg",
    hints: [
      "Usei um objeto estranho como prova para demonstrar minha lealdade.",
      "Meus aliados mais fiéis eram conhecidos por feitos incríveis em combate.",
      "Tive a chance de mudar meu destino com um único golpe, mas recusei.",
      "Alguns de meus dons eram a música e a poesia.",
      "Já me finji de louco.",
      "Meu pai se chamava Jessé.",
      "Derrotei Golias com uma funda.",
      "Fui o segundo rei de Israel.",
      "Fui pastor de ovelhas antes de ser rei.",
    ],
  },
  {
    name: "Lucas",
    image: "Luke.jpg",
    hints: [
      "Em meu evangelho registrei a genealogia de Jesus por meio de José.",
      "Apenas eu estava com Paulo em Roma quando ele estava prestes a receber sua sentença.",
      "Apesar de ter escrito um dos evangelhos, provavelmente não fui testemunha ocular dos acontecimentos.",
      "Os dois livros que escrevi foram direcionados a meu amigo Teófilo.",
      "Escrevi Atos dos Apóstolos.",
      "Fui identificado como 'o médico amado'.",
      "Sou médico.",
      "Escrevi o terceiro evangelho da Bíblia.",
      "Fui companheiro do apóstolo Paulo.",
    ],
  },
  {
    name: "Jonas",
    image: "Jonah.jpg",
    hints: [
      "Minha história foi mencionada por Jesus.",
      "Meu livro termina com uma pergunta feita por Deus, sem resposta registrada.",
      "Meu nome significa 'Pomba' em hebraico.",
      "Fiquei triste pela morte de uma planta.",
      "Depois de ter passado por uma experiência assustadora, ele finalmente obedeceu a Deus.",
      "Enquanto dormia em um barco, uma tempestade ameaçou afundá-lo'.",
      "Tentou fugir da missão que Deus lhe deu.",
      "Deus mandou que ele fosse pregar em Nínive.",
      "Foi engolido por um grande peixe e ficou três dias dentro dele.",
    ],
  },
  {
    name: "Paulo",
    image: "Paul.jpg",
    hints: [
      "Eu tinha um problema nas vistas.",
      "Recebi uma visão de Cristo no caminho para Damasco.",
      "Sobrevivi a um naufrágio.",
      "Fui preso várias vezes por pregar o evangelho.",
      "Fiquei cego por três dias.",
      "Me considerava o menos importante dos apóstolos",
      "Fui chamado de 'apóstolo dos gentios'.",
      "Antes de me tornar cristão, persegui os seguidores de Jesus.",
      "Meu nome original era Saulo.",
    ],
  },
  {
    name: "Ester",
    image: "Esther.jpg",
    hints: [
      "O livro que conta minha história não menciona diretamente o nome de Deus.",
      "O rei estendeu o cetro dourado para mim como sinal de favor.",
      "Meu marido foi Assuero (Xerxes I).",
      "O vilão da minha história tentou enforcar meu primo, mas acabou enforcado no mesmo lugar.",
      "Fiz um jejum de três dias antes de ir falar com o rei.",
      "Meu nome original era Hadassa.",
      "Tive que me apresentar ao rei sem ser chamada, o que poderia custar minha vida.",
      "Meu primo e tutor se chamava Mordecai.",
      "Fui rainha da Pérsia e salvei meu povo de um grande perigo.",
    ],
  },
  {
    name: "Abraão",
    image: "Abraão.jpg",
    hints: [
      "Recebi a visita de três homens que anunciaram o nascimento de meu filho.",
      "Comprei a caverna de Macpela.",
      "Tentei 'ajudar' a promessa tendo um filho com minha serva.",
      "Fiz a primeira oração registrada na Bíblia.",
      "Saí da terra de Ur dos Caldeus para uma terra que Deus me mostraria.",
      "Tive um filho chamado em idade avançada.",
      "Deus prometeu que minha descendência seria tão numerosa quanto as estrelas.",
      "Sou chamado de 'pai dos que tem fé'.",
      "Meu nome antes de ser mudado era Abrão.",
    ],
  },
  {
    name: "Abel",
    image: "Adam.jpg",
    hints: [
      "Meu nome significa 'vapor' ou 'sopro'.",
      "Embora eu ainda esteja morto, ainda falo.",
      "Fui pastor de ovelhas.",
      "Deixei um exemplo de justiça ao oferecer um sacrifício aceitável a Deus.",
      "Minha oferta foi aceita, enquanto a de meu irmão não foi.",
      "Meu irmão ficou com ciúmes de mim.",
      "Deus avisou meu irmão para que não alimentasse o ressentimento.",
      "Fui o primeiro homem assassinado na história.",
      "Fui morto pelo meu irmão Caim.",
    ],
  },
  {
    name: "Salomão",
    image: "Salomão.jpg",
    hints: [
      "Minha mãe garantiu que eu subisse ao trono antes do meu meio-irmão Adonias.",
      "Minha frota de navios fazia comércio com Társis e trazia ouro, prata, marfim, macacos e pavões.",
      "Havia doze governadores sobre Israel que coletavam tributos para sustentar minha corte.",
      "Julguei duas mulheres que brigavam por um bebê, propondo cortá-lo ao meio.",
      "Fui o terceiro rei de Israel.",
      "Tive 700 esposas e 300 concubinas.",
      "No final da minha vida, me afastei de Deus por influência de minhas esposas estrangeiras.",
      "Escrevi Eclesiastes e Provérbios.",
      "Sou conhecido como o homem mais sábio que já existiu.",
    ],
  },
  {
    name: "Neemias",
    image: "Neemiah.jpg",
    hints: [
      "Lutei contra o casamento com estrangeiros entre os israelitas.",
      "Meus inimigos eram Sambalá e Tobias.",
      "Fiz uma rápida oração antes de fazer um pedido.",
      "Fui responsável por uma obra que durou 52 dias.",
      "Organizei turnos para que alguns construíssem e outros protegessem os trabalhadores.",
      "Eu era copeiro do rei da Pérsia.",
      "Fiz o povo de Israel renovar sua aliança com Deus.",
      "Liderei a reconstrução dos muros de Jerusalém após o exílio babilônico.",
      "Trabalhei ao lado de Esdras.",
    ],
  },
  {
    name: "Josias",
    image: "Josias.jpg",
    hints: [
      "Fui morto em uma batalha contra o faraó Neco do Egito.",
      "Dei ordens para restaurar o templo.",
      "Encontrei o Livro da Lei que há muito tempo não seguíamos.",
      "Ordenei a destruição dos ídolos e altares pagãos em Judá.",
      "Meu coração foi sensível, e Deus prometeu que eu morreria antes de ver a destruição de Jerusalém.",
      "Celebrei a maior Páscoa que Israel já teve desde os tempos dos juízes.",
      "Fiz uma grande reforma religiosa para eliminar a idolatria.",
      "Fui rei de Judá e comecei a reinar com apenas oito anos de idade.",
      "Meu avô fez coisas muito más, porém ele foi perdoado por Jeová.",
    ],
  },
  {
    name: "Josué",
    image: "",
    hints: [
      "Meu nome original era Oséias, mas um grande líder de uma nação o mudou.",
      "Ordenei que o povo marchasse ao redor das muralhas de Jericó por sete dias.",
      "Dei instruções detalhadas sobre a divisão da Terra Prometida entre as tribos de Israel.",
      "Enviei dois espias para explorar Jericó.",
      "Fiz um pacto de paz com os Gibeonitas sem consultar a Jeová antes.",
      "Deus me ajudou em uma batalha fazendo o sol ficar parado",
      "Liderei os israelitas na travessia do rio Jordão quando ele estava cheio.",
      "Assumi a liderança de Israel após a morte de Moisés.",
      "Eu e Calebe fomos os únicos espias que trouxeram um relatório positivo sobre a Terra Prometida.",
    ],
  },

{
    name: "Rute",
    image: "Ruth.jpg",
    hints: [
      "Fui beneficiada pela lei do resgatador.",
      "Fui bisavó do rei Davi.",
      "Sou uma das poucas mulheres mencionadas na genealogia de Jesus.",
      "Meu nome significa 'amizade' ou 'companheirismo'.",
      "Minha história acontece no período dos juízes.",
      "Minha lealdade foi expressa na frase: 'Seu povo será meu povo, e seu Deus será meu Deus'.",
      "Trabalhei recolhendo espigas nos campos de Boaz para sustentar minha sogra.",
      "Meu marido morreu, e escolhi seguir minha sogra para um país estrangeiro.",
      "Casei-me com Boaz e me tornei parte da linhagem do Messias.",
    ],
  },

{
    name: "Daniel",
    image: "Daniel.jpg",
    hints: [
      "Minha sabedoria foi comparada à de um anjo pelo rei.",
      "Recebi visões proféticas sobre reinos futuros, incluindo um com dez chifres.",
      "Interpretei um sonho de Nabucodonosor sobre uma grande árvore.",
      "Meu livro menciona um período de 70 semanas proféticas.",
      "Pedi a meus amigos que orassem quando um rei exigiu que interpretasse um sonho sem contar qual era o sonho.",
      "Um rei pagão me chamou pelo nome de um de seus deuses: Beltessazar.",
      "Fui lançado em uma cova cheia de leões, mas saí ileso.",
      "Eu tinha três amigos chamados Sadraque, Mesaque e Abednego.",
      "Recusei comer os alimentos do rei.",
    ],
  },
  {
    name: "Ana",
    image: "",
    hints: [
      "Meu cântico profético menciona um rei antes mesmo de Israel ter um.",
      "Eu e minha família fazíamos uma viagem anual a Silo.",
      "Meu cântico inspirou um dos cânticos mais famosos do Novo Testamento.",
      "Prometi que, se Deus me desse um filho, ele seria dedicado a Ele por toda a vida.",
      "Meu filho foi um dos maiores profetas de Israel.",
      "Fiz uma oração silenciosa no templo, o que levou o sacerdote a pensar que eu estava embriagada.",
      "Meu marido tinha outra esposa, que frequentemente me provocava.",
      "Meu filho ouviu a voz de Deus quando ainda era criança.",
      "Sou mãe de Samuel.",
    ],
  },

{
    name: "Gideão",
    image: "",
    hints: [
      "Fiz um ídolo de ouro que se tornou um laço para meu povo.",
      "Construí um altar chamado 'Jeová-Shalom'.",
      "Tive de escolher meus guerreiros a partir da forma que bebiam a água do rio.",
      "Recusei a oferta de me tornar rei de Israel.",
      "Pedi um sinal de Deus usando um velo de lã.",
      "Destruí um altar de Baal, e por isso fui chamado de Jerubaal.",
      "Fui chamado de 'homem valente' por um anjo, mesmo me considerando fraco.",
      "Deus reduziu meu exército de milhares para apenas 300 soldados.",
      "Fui um dos juízes de Israel.",
    ],
  },

{
    name: "Timóteo",
    image: "",
    hints: [
      "Tive um problema de saúde que Paulo sugeriu tratar com um pouco de vinho.",
      "Meu nome significa 'aquele que honra a Deus'.",
      "Fui deixado para liderar a congregação de Éfeso.",
      "Fui um dos companheiros mais próximos do apóstolo Paulo.",
      "Apesar de jovem, recebi grandes responsabilidades.",
      "Minha mãe era judia, mas meu pai era grego.",
      "Desde a infância fui ensinado nas Escrituras.",
      "Fui circuncidado por Paulo para evitar obstáculos ao meu ministério.",
      "Recebi duas cartas de Paulo com conselhos sobre liderança.",
    ],
  },

{
    name: "Jeremias",
    image: "Jeremias.jpg",
    hints: [
      "Fui proibido por Deus de me casar ou ter filhos.",
      "Testemunhei a destruição do Templo de Salomão.",
      "Fui chamado por Deus antes mesmo de nascer.",
      "Fiz um jugo de madeira para simbolizar a escravidão de Israel.",
      "Adverti repetidamente os reis de Judá, mas fui ignorado.",
      "Me tornei profeta ainda jovem.",
      "Escrevi um livro de lamentações sobre a queda de Jerusalém.",
      "Fui lançado em uma cisterna lamacenta e deixado para morrer.",
      "Fui um dos principais profetas de Judá antes do exílio babilônico.",
    ],
  },
  {
    name: "Enoque",
    image: "",
    hints: [
      "Nasci na sétima geração da família de Adão.",
      "Meu nome aparece no livro de Judas, no contexto de uma profecia.",
      "Profetizei as seguintes palavras: “Vejam! Jeová veio com as suas santas miríades para executar julgamento contra todos.",
      "Minha vida foi misteriosa, e muitos especulam sobre meu destino.",
      "Minha genealogia é registrada no livro de Gênesis.",
      "Fui pai de Matusalém, o homem mais velho da Bíblia.",
      "Vivi 365 anos antes de desaparecer.",
      "Fui conhecido por pregar com coragem.",
      "Fui levado por Deus sem passar pela morte.",
    ],
  },

{
    name: "Sara",
    image: "",
    hints: [
      "Fui sepultada em Macpela, em um campo comprado por meu marido.",
      "Recebi a visita de anjos que anunciaram algo impossível para mim.",
      "Fui uma das poucas mulheres mencionadas na galeria da fé em Hebreus.",
      "Fui tomada por faraó e por Abimeleque como esposa, mas Deus me protegeu.",
      "Dei uma serva a meu marido para que ele tivesse um filho.",
      "Meu marido riu de algo que Jeová disse a ele.",
      "Meu nome foi trocado, meu nome antigo significava “briguenta“",
      "Meu novo nome significa “princesa“.",
      "Sou esposa de Abraão e mãe de Isaque.",
    ],
  },

{
    name: "Jó",
    image: "",
    hints: [
      "Meu livro contém longos discursos poéticos e diálogos profundos.",
      "Tive um bom amigo chamado Eliú.",
      "Minha história mostra um debate entre um anjo rebelde e Deus.",
      "Eu tinha péssimos amigos chamados Elifaz, Bildade e Zofar",
      "Minha esposa me disse para amaldiçoar a Deus e morrer.",
      "Tive amigos que tentaram me convencer de que minha dor era culpa minha.",
      "Fui um homem muito rico e influente no Oriente.",
      "Fiquei doente e perdi todos os meus bens e filhos.",
      "Mesmo sofrendo, continuei fiel a Deus e fui recompensado no final.",
    ],
  },
  {
    name: "Mefibosete",
    image: "",
    hints: [
      "Meu nome significa 'exterminador da vergonha'.",
      "Morei em Lo-Debar antes de ser chamado pelo rei.",
      "Eu era neto de um rei que perdeu o favor de Jeová.",
      "Fui alvo de uma mentira que quase me fez perder tudo.",
      "Um servo enganou o rei sobre minhas intenções para tomar minhas terras.",
      "Minha história envolve lealdade e misericórdia de um rei.",
      "Fui convidado a sempre comer à mesa do rei.",
      "Fiquei aleijado ainda criança por causa de uma queda.",
      "Fui poupado por Davi por causa de uma aliança com meu pai, Jonatã.",
    ],
  },
  
  {
    name: "João",
    image: "",
    hints: [
      "Dentre meus amigos, fui o único que morreu de velhice e não por perseguição direta.",
      "Minha escrita usa muitos simbolismos e contrastes, como 'luz e trevas'.",
      "Estive presente na transfiguração de Jesus.",
      "Meu livro começa assim: “No início era a Palavra, e a Palavra estava com Deus, e a Palavra era um deus.“.",
      "Fui o autor do último livro da Bíblia, escrito na ilha de Patmos.",
      "Fui chamado de 'Filho do Trovão'.",
      "Fui o autor de três cartas curtas na Bíblia.",
      "Sou chamado de 'o discípulo a quem Jesus amava'.",
      "Escrevi um dos quatro evangelhos.",
    ],
  },
  {
    name: "Adão",
    image: "",
    hints: [
      "Meu nome significa 'homem' ou 'terra' em hebraico.",
      "O solo foi amaldiçoado por minha causa.",
      "Fui expulso do lugar onde vivia por desobedecer a Deus.",
      "Minha esposa foi feita a partir de uma parte do meu corpo.",
      "Um anjo com uma espada de fogo me impediu de voltar para o meu antigo lar.",
      "Não tive mãe.",
      "Fui formado a partir do pó da terra.",
      "Jeová me designou para dar nome aos animais.",
      "Fui o primeiro homem da história.",
    ],
  },
  {
    name: "Levi",
    image: "Levi.jpg",
    hints:[
      "Meus filhos são Coate, Merari e Gérson.",
      "Meus irmãos e eu tomamos uma atitude radical contra a cidade de Siquém.",
      "Sou um dos filhos de Jacó e Lea.",
      "Meu pai fez uma profecia sobre mim e meu irmão no fim da vida, amaldiçoando nossa ira.",
      "Sou avô de Moisés.",
      "Meu nome aparece entre os doze filhos de Israel.",
      "Meus descendentes foram escolhidos para servir como sacerdotes.",
      "Minha tribo não recebeu uma herança de terra em Israel.",
    ],
  },
    {
      name: "Natã",
      image: "",
      hints: [
        "Chamei Salomão de Jedidias, que significa “Amado de Jah”.",
        "Eu tive um papel fundamental na sucessão de Salomão ao trono.",
        "Unji Salomão como rei de Israel.",
        "Ajudei a escrever parte da história do reinado de Davi.",
        "Fui um profeta no tempo dos reis Davi e Salomão.",
        "Incentivei um amigo a fazer uma grande obra, porém tive que anunciar que ela não seria feita por ele.",
        "Deus me enviou para repreender Davi por seu pecado com Bate-Seba.",
        "Contei a parábola do homem rico que roubou a cordeira do pobre.",
        "Apontei o pecado de Davi, dizendo: 'Tu és o homem!'.",
      ],
    },
    {
      name: "Eliseu",
      image: "",
      hints: [
        "Após uma oração minha, o exército inimigo foi atingido com cegueira mental.",
        "Mesmo depois de morto, um milagre aconteceu com meu corpo.",
        "Realizei mais milagres do que qualquer outro profeta das Escrituras Gregas.",
        "Orei para Jeová abrir os olhos de meu ajudante.",
        "Pedi por uma porção dobrada do espírito de meu mestre.",
        "Fiz o ferro de um machado flutuar na água.",
        "Purifiquei as águas de Jericó com sal.",
        "Orientei Naamã a se lavar sete vezes no Jordão para ser curado da lepra.",
        "Fui discípulo e sucessor do profeta Elias.",
      ],
    },
    {
      name: "Eúde",
      image:"",
      hints:[
        "Fui um juiz de Israel, mas sou mencionado poucas vezes na Bíblia.",
        "Após cumprir minha missão, fugi silenciosamente pela varanda.",
        "Fui encarregado de entregar tributos ao rei de Moabe.",
        "Minha história está no livro de Juízes, capítulo 3.",
        "O fato de eu ser canhoto me ajudou em uma missão.",
        "Libertador enviado por Deus para salvar Israel da opressão moabita.",
        "Depois de completar minha missão, escapei pelos ídolos de Gilgal.",
        "Matei o rei Eglom com uma espada escondida sob minhas vestes.",
        "Após minha vitória, Israel teve paz por 80 anos.",
      ],
    },
   
  {
    name: "Ezequiel",
    image: "Ezekiel.jpg",
    hints: [
      "Fui chamado para ser profeta enquanto estava no exílio.",
      "Minha esposa morreu e Deus me proibiu de lamentar por ela.",
      "Deus me ordenou que ficasse mudo por um período de tempo.",
      "Um anjo de cobre me mostrou um lugar impresisonante.",
      "Tive uma visão impressionante perto de um rio.",
      "Meu livro menciona uma nova estrutura do templo.",
      "Vi um vale cheio de ossos secos ganhando vida.",
      "Vi anjos com quatro faces.",
      "Tive uma visão de um carro celestial com querubins.",
    ],
  },
  {
    name: "Mateus",
    image: "Matthew.jpg",
    hints: [
      "Fiz uma festa que incomodou meus inimigos, fazendo-os falar mal de mim e meus amigos.",
      "Meu pai se chama Alfeu.",
      "Eu trabalhava para os romanos mas era mal visto pelos judeus.",
      "Meu evangelho é o primeiro na ordem do Novo Testamento.",
      "Citei muitas profecias das Escrituras Hebraicas para provar que Jesus cumpriu todas elas.",
      "Meu antigo trabalho era muito odiado pelo povo judeu.",
      "Meu livro contém vários discursos muito importantes.",
      "Escrevi um evangelho destacando Jesus como o Messias prometido aos judeus.",
      "Eu era cobrador de impostos antes de ser discípulo de Jesus.",
    ],
  },
  
  {
    name: "Marcos",
    image: "",
    hints: [
      "Minha mãe hospedava reuniões de cristãos em sua casa.",
      "Meu estilo de escrita é mais dinâmico.",
      "Meu evangelho usa a palavra 'imediatamente' com frequência.",
      "Fui motivo de uma briga entre dois amigos.",
      "Sou mencionado em algumas cartas de Paulo como seu ajudante.",
      "Pedro tinha afeição por mim, chegou a me chamar de “meu filho“.",
      "Possivelmente eu era o jovem que fugiu nu na ocasião que prenderam Jesus.",
      "Viajei com Paulo e Barnabé em uma de suas missões.",
      "Escrevi o segundo evangelho do Novo Testamento.",
    ],
  },
  
  {
    name: "Judas Iscariotes",
    image: "",
    hints: [
      "Não gostei quando ungiram meu amigo com óleo perfumado.",
      "Eu era responsável pelo dinheiro do grupo dos discípulos.",
      "Minhas ações ruins foram profetizadas.",
      "Tentei devolver o pagamento que recebi, mas já era tarde demais.",
      "De acordo com as palavras de Jesus: Seria melhor que eu nunca tivesse nascido.",
      "Jesus me disse para fazer algo depressa.",
      "Os líderes religiosos ficaram felizes com minha traição.",
      "Aceitei 30 moedas de prata para trair Jesus.",
      "Sou o discípulo que traiu Jesus com um beijo.",
    ],
  },
  {
    name: "Jesus",
    image: "",
    hints: [
      "Já fui chamado de Abadon na Bíblia.",
      "Citei um versículo do Salmo 22 enquanto estava em grande sofrimento.",
      "Quando morri, havia comigo uma placa com inscrições em três idiomas.",
      "Chorei sobre uma cidade específica antes de minha morte.",
      "Ajudei uma pessoa sem sequer vê-a pessoalmente.",
      "Meu nascimento deixou um rei furioso.",
      "Uma profecia sobre mim menciona que fui 'chamado do Egito'.",
      "Sou muito parecido com meu pai.",
      "Sou o filho primogênito de Jeová.",
    ],
  },
  

];