export const characters = [
  {
    "name": "Maria",
    "image": "https://cms-imgp.jw-cdn.org/img/p/1102013264/univ/art/1102013264_univ_lsr_lg.jpg",
    "hints": [
      "Uma profecia disse que uma longa espada me atravessaria.",
      "Meu esposo aceitou um grande desafio por causa de um sonho.",
      "Ofereci um par de rolas ou dois pombos novos quando fui ao templo.",
      "Fiquei por três dias sem saber onde meu filho estava.",
      "Recebi uma visita inesperada que mudou minha vida para sempre.",
      "Fugi para outro país para proteger meu filho de um rei cruel.",
      "Tive um filho apesar de virgem.",
      "Meu marido era carpinteiro e ensinou essa profissão a meu filho.",
      "Sou lembrada como a mãe do homem mais importante da história."
    ]
  },
  {
    name: "Pedro",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013267/univ/art/1102013267_univ_lsr_lg.jpg",
    hints: [
      "Paguei um imposto com uma moeda tirada de um peixe que eu pesquei.",
      "Tive uma visão de um lençol cheio de animais, mudando meu entendimento sobre um assunto importante.",
      "Fui um dos primeiros discípulos chamados por Jesus.",
      "Fui chamado de cinco maneiras diferentes na Bíblia entre elas estão: Simeão, Simão e Cefas.",
      "Fui libertado da prisão por um anjo enquanto os irmãos oravam por mim.",
      "Fui repreendido publicamente por um amigo meu.",
      "Cortei a orelha de um soldado no Getsêmani.",
      "Andei sobre as águas, mas afundei quando duvidei.",
      "Neguei Jesus três vezes antes do galo cantar.",
    ],
  },

{
    name: "José do Egito",
    image: "https://cms-imgp.jw-cdn.org/img/p/2015327/univ/art/2015327_univ_lsr_lg.jpg",
    hints: [
      "Um dos meus nomes era Zafenate-Paneia.",
      "Sonhei que a Lua e o Sol se curvavam perante uma estrela.",
      "Fiquei preso com o chefe dos padeiros e o chefe dos copeiros.",
      "Dei um conselho ao faraó que salvou o Egito da fome.",
      "Deus transformou o mal que sofri em algo bom.",
      "Ganhei uma túnica colorida de presente do meu pai.",
      "Fui vendido como escravo por meus próprios irmãos.",
      "Cheguei a ser o segundo homem mais poderoso do Egito.",
      "Fui acusado injustamente e lançado na prisão.",
    ],
  },

{
    name: "Miriã",
    image: "https://cms-imgp.jw-cdn.org/img/p/501500100/univ/wpub/501500100_univ_lsr_lg.jpg",
    hints: [
      "Meu nome junto com os dos meus irmãos é mencionado no livro de Miqueias.",
      "Sou a primeira mulher chamada de profetisa na Bíblia.",
      "Sou filha de Anrão e Joquebede.",
      "Liderei as mulheres em um cântico após um grande livramento.",
      "Fui castigada com lepra por ter sido rebelde, mas fui perdoada.",
      "Cantei e toquei tamborins após a travessia do mar Vermelho.",
      "Ajudei a salvar meu irmão quando ele era um bebê.",
      "Minha família liderou a saída do povo do Egito.",
      "Sou irmã de Moisés e Arão.",
    ],
  },

  {
    "name": "Samuel",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwsDzdYtCjNgZP56863m1KS5F2UMi5_DGqaw&s",
    "hints": [
      "Minha mãe cantou um cântico que mais tarde se refletiria em outra história famosa.",
      "Meus dois filhos me trouxeram muita tristeza.",
      "Fui o último da minha função antes de um novo sistema de governo.",
      "Exortei um rei quando ele poupou o que deveria destruir.",
      "Untei com óleo dois homens que se tornaram reis.",
      "Uma voz misteriosa me chamou durante a noite, mas eu não sabia quem era.",
      "Fui um profeta e um nazireu.",
      "Minha mãe fez um voto antes mesmo de eu nascer.",
      "Fui um dos maiores juízes e profetas de Israel."
    ]
  },
  {
    "name": "Noemi",
    "image": "https://cms-imgp.jw-cdn.org/img/p/1102013250/univ/art/1102013250_univ_cnt_3_xl.jpg",
    "hints": [
      "Meu nome significa algo, mas cheguei a rejeitá-lo por um tempo.",
      "Minha decisão impactou a linhagem do maior rei de Israel.",
      "Fui acompanhada por alguém que fez um voto muito famoso.",
      "Passei um período vivendo em uma terra estrangeira.",
      "Ajudei a planejar um encontro decisivo para minha família.",
      "Fui restaurada quando um parente redentor apareceu.",
      "Minha história está registrada em um dos livros mais curtos da Bíblia.",
      "Uma grande tragédia me fez mudar de país.",
      "Sou lembrada como sogra de uma mulher fiel e admirável."
    ]
  },
  {
    "name": "Saul",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX00oxe3rAmPmDa1Fgnu6WiMOJZ2ZkRULs-w&s",
    "hints": [
      "Uma vez, profetizei entre um grupo inesperado de pessoas.",
      "Comecei minha trajetória modesto, mas mudei com o tempo.",
      "Fiz algo que não me cabia e isso me custou muito caro.",
      "Não obedeci completamente uma ordem e fui repreendido publicamente.",
      "A música me acalmava.",
      "Eu poderia ter sido morto em uma situação bem constrangedora.",
      "Pelo ciúme, persegui alguém que não era meu inimigo.",
      "Morri em combate junto com um dos meus filhos.",
      "Fui o primeiro rei de Israel."
    ]
  },
  {
    "name": "Sansão",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX00oxe3rAmPmDa1Fgnu6WiMOJZ2ZkRULs-w&s",
    "hints": [
      "Fui obrigado a seguir regras específicas desde antes do meu nascimento.",
      "Contei um enigma sobre algo doce vindo de algo forte.",
      "Capturei 300 raposas e fiz um incêndio em um campo com elas.",
      "Fui traído por alguém que dizia me amar.",
      "Fui cegado pelos meus inimigos.",
      "Matei 1000 homens com uma arma nada convencional.",
      "Derrotei um grande número de inimigos em um ato final.",
      "Minha força não vinha de mim, mas de um voto especial.",
      "Meu nome é lembrado entre os juízes de Israel."
    ]
  },
  {
    "name": "Ezequias",
    "image": "https://cms-imgp.jw-cdn.org/img/p/502012425/univ/art/502012425_univ_lsr_md.jpg",
    "hints": [
      "Fui aconselhado pelo profeta Isaías.",
      "Mandei destruir a serpente de cobre que Moisés tinha feito.",
      "Fui responsável pela construção de umg rande aqueduto.",
      "Fui imprudente ao mostrar as riquezas do reino aos mensageiros de Babilônia.",
      "Recebi uma mensagem dura sobre minha saúde, mas ela foi revertida.",
      "Vi um grande exército ser derrotado sem precisar lutar.",
      "Fui elogiado como um dos melhores reis de Judá.",
      "Destruí altares idólatras para restaurar a adoração verdadeira.",
      "Meu inimigo foi Senaqueribe, filho de Sargão II."
    ]
  },
  
  {
    name: "Moisés",
    image: "https://cms-imgp.jw-cdn.org/img/p/2013086/univ/art/2013086_univ_lsr_lg.jpg",
    hints: [
      "Um estrangeiro me deu um novo lar e um novo nome de família",
      "Uma parte do meu corpo precisava ser sustentada por outros para garantir uma vitória",
      "Minha morte foi supervisionada, mas nunca testemunhada por outro humano",
      "Minha esposa se chamava Zípora",
      "Meu irmão se chamava Arão.",
      "Golpeei uma rocha para dela sair água.",
      "Fui escolhido por Deus para libertar os israelitas do Egito.",
      "Abri o Mar Vermelho com a ajuda de Jeová.",
      "Recebi os Dez Mandamentos.",
    ],
  },
  {
    name: "Davi",
    image: "https://cms-imgp.jw-cdn.org/img/p/202022173/univ/art/202022173_univ_lsr_lg.jpg",
    hints: [
      "Usei um objeto estranho como prova para demonstrar minha lealdade.",
      "Meus aliados mais fiéis eram conhecidos por feitos incríveis em combate.",
      "Tive a chance de mudar meu destino com um único golpe, mas recusei.",
      "Alguns de meus dons eram a música e a poesia.",
      "Já me finji de louco.",
      "Meu pai se chamava Jessé.",
      "Derrotei Golias com uma funda.",
      "Fui o segundo rei de Israel.",
      "Fui pastor de ovelhas antes de ser rei.",
    ],
  },
  {
    name: "Lucas",
    image: "https://cms-imgp.jw-cdn.org/img/p/2014006/univ/art/2014006_univ_cnt_2_xl.jpg",
    hints: [
      "Em meu evangelho registrei a genealogia de Jesus por meio de José.",
      "Apenas eu estava com Paulo em Roma quando ele estava prestes a receber sua sentença.",
      "Apesar de ter escrito um dos evangelhos, provavelmente não fui testemunha ocular dos acontecimentos.",
      "Os dois livros que escrevi foram direcionados a meu amigo Teófilo.",
      "Escrevi Atos dos Apóstolos.",
      "Fui identificado como 'o médico amado'.",
      "Sou médico.",
      "Escrevi o terceiro evangelho da Bíblia.",
      "Fui companheiro do apóstolo Paulo.",
    ],
  },
  {
    name: "Jonas",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013259/univ/art/1102013259_univ_cnt_3_xl.jpg",
    hints: [
      "Minha história foi mencionada por Jesus.",
      "Meu livro termina com uma pergunta feita por Deus, sem resposta registrada.",
      "Meu nome significa 'Pomba' em hebraico.",
      "Fiquei triste pela morte de uma planta.",
      "Depois de ter passado por uma experiência assustadora, ele finalmente obedeceu a Deus.",
      "Enquanto dormia em um barco, uma tempestade ameaçou afundá-lo'.",
      "Tentou fugir da missão que Deus lhe deu.",
      "Deus mandou que ele fosse pregar em Nínive.",
      "Foi engolido por um grande peixe e ficou três dias dentro dele.",
    ],
  },
  {
    name: "Paulo",
    image: "https://cms-imgp.jw-cdn.org/img/p/2018326/univ/art/2018326_univ_lsr_lg.jpg",
    hints: [
      "Eu tinha um problema nas vistas.",
      "Recebi uma visão de Cristo no caminho para Damasco.",
      "Sobrevivi a um naufrágio.",
      "Fui preso várias vezes por pregar o evangelho.",
      "Fiquei cego por três dias.",
      "Me considerava o menos importante dos apóstolos",
      "Fui chamado de 'apóstolo dos gentios'.",
      "Antes de me tornar cristão, persegui os seguidores de Jesus.",
      "Meu nome original era Saulo.",
    ],
  },
  {
    name: "Ester",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013262/univ/art/1102013262_univ_cnt_2_xl.jpg",
    hints: [
      "O livro que conta minha história não menciona diretamente o nome de Deus.",
      "O rei estendeu o cetro dourado para mim como sinal de favor.",
      "Meu marido foi Assuero (Xerxes I).",
      "O vilão da minha história tentou enforcar meu primo, mas acabou enforcado no mesmo lugar.",
      "Fiz um jejum de três dias antes de ir falar com o rei.",
      "Meu nome original era Hadassa.",
      "Tive que me apresentar ao rei sem ser chamada, o que poderia custar minha vida.",
      "Meu primo e tutor se chamava Mordecai.",
      "Fui rainha da Pérsia e salvei meu povo de um grande perigo.",
    ],
  },
  {
    name: "Abraão",
    image: "https://cms-imgp.jw-cdn.org/img/p/2016122/univ/art/2016122_univ_lsr_lg.jpg",
    hints: [
      "Recebi a visita de três homens que anunciaram o nascimento de meu filho.",
      "Comprei a caverna de Macpela.",
      "Tentei 'ajudar' a promessa tendo um filho com minha serva.",
      "Fui testado por Deus para oferecer meu filho em sacrifício.",
      "Saí da terra de Ur dos Caldeus para uma terra que Deus me mostraria.",
      "Tive um filho chamado em idade avançada.",
      "Deus prometeu que minha descendência seria tão numerosa quanto as estrelas.",
      "Sou chamado de 'pai dos que tem fé'.",
      "Meu nome antes de ser mudado era Abrão.",
    ],
  },
  {
    name: "Abel",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013271/univ/art/1102013271_univ_cnt_2_xl.jpg",
    hints: [
      "Meu nome significa 'vapor' ou 'sopro'.",
      "Embora eu ainda esteja morto, ainda falo.",
      "Fui pastor de ovelhas.",
      "Deixei um exemplo de justiça ao oferecer um sacrifício aceitável a Deus.",
      "Minha oferta foi aceita, enquanto a de meu irmão não foi.",
      "Meu irmão ficou com ciúmes de mim.",
      "Deus avisou meu irmão para que não alimentasse o ressentimento.",
      "Fui o primeiro homem assassinado na história.",
      "Fui morto pelo meu irmão Caim.",
    ],
  },
  {
    name: "Salomão",
    image: "https://cms-imgp.jw-cdn.org/img/p/1101978118/univ/art/1101978118_univ_lsr_lg.jpg",
    hints: [
      "Minha mãe garantiu que eu subisse ao trono antes do meu meio-irmão Adonias.",
      "Minha frota de navios fazia comércio com Társis e trazia ouro, prata, marfim, macacos e pavões.",
      "Havia doze governadores sobre Israel que coletavam tributos para sustentar minha corte.",
      "Julguei duas mulheres que brigavam por um bebê, propondo cortá-lo ao meio.",
      "Fui o terceiro rei de Israel.",
      "Tive 700 esposas e 300 concubinas.",
      "No final da minha vida, me afastei de Deus por influência de minhas esposas estrangeiras.",
      "Escrevi Eclesiastes e Provérbios.",
      "Sou conhecido como o homem mais sábio que já existiu.",
    ],
  },
  {
    name: "Neemias",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102016077/univ/art/1102016077_univ_lsr_lg.jpg",
    hints: [
      "Lutei contra o casamento com estrangeiros entre os israelitas.",
      "Meus inimigos eram Sambalá e Tobias.",
      "Fiz uma rápida oração antes de fazer um pedido.",
      "Fui responsável por uma obra que durou 52 dias.",
      "Organizei turnos para que alguns construíssem e outros protegessem os trabalhadores.",
      "Eu era copeiro do rei da Pérsia.",
      "Fiz o povo de Israel renovar sua aliança com Deus.",
      "Liderei a reconstrução dos muros de Jerusalém após o exílio babilônico.",
      "Trabalhei ao lado de Esdras.",
    ],
  },
  {
    name: "Josias",
    image: "https://cms-imgp.jw-cdn.org/img/p/502012435/univ/art/502012435_univ_lsr_md.jpg",
    hints: [
      "Fui morto em uma batalha contra o faraó Neco do Egito.",
      "Dei ordens para restaurar o templo.",
      "Encontrei o Livro da Lei que há muito tempo não seguíamos.",
      "Ordenei a destruição dos ídolos e altares pagãos em Judá.",
      "Meu coração foi sensível, e Deus prometeu que eu morreria antes de ver a destruição de Jerusalém.",
      "Celebrei a maior Páscoa que Israel já teve desde os tempos dos juízes.",
      "Fiz uma grande reforma religiosa para eliminar a idolatria.",
      "Fui rei de Judá e comecei a reinar com apenas oito anos de idade.",
      "Meu avô fez coisas muito más, porém ele foi perdoado por Jeová.",
    ],
  },
  {
    name: "Josué",
    image: "https://cms-imgp.jw-cdn.org/img/p/502012394/univ/art/502012394_univ_lsr_lg.jpg",
    hints: [
      "Meu nome original era Oséias, mas um grande líder de uma nação o mudou.",
      "Ordenei que o povo marchasse ao redor das muralhas de Jericó por sete dias.",
      "Dei instruções detalhadas sobre a divisão da Terra Prometida entre as tribos de Israel.",
      "Enviei dois espias para explorar Jericó.",
      "Fiz um pacto de paz com os Gibeonitas sem consultar a Jeová antes.",
      "Deus me ajudou em uma batalha fazendo o sol ficar parado",
      "Liderei os israelitas na travessia do rio Jordão quando ele estava cheio.",
      "Assumi a liderança de Israel após a morte de Moisés.",
      "Eu e Calebe fomos os únicos espias que trouxeram um relatório positivo sobre a Terra Prometida.",
    ],
  },

{
    name: "Rute",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013250/univ/art/1102013250_univ_cnt_4_xl.jpg",
    hints: [
      "Fui beneficiada pela lei do resgatador.",
      "Fui bisavó do rei Davi.",
      "Sou uma das poucas mulheres mencionadas na genealogia de Jesus.",
      "Meu nome significa 'amizade' ou 'companheirismo'.",
      "Minha história acontece no período dos juízes.",
      "Minha lealdade foi expressa na frase: 'Seu povo será meu povo, e seu Deus será meu Deus'.",
      "Trabalhei recolhendo espigas nos campos de Boaz para sustentar minha sogra.",
      "Meu marido morreu, e escolhi seguir minha sogra para um país estrangeiro.",
      "Casei-me com Boaz e me tornei parte da linhagem do Messias.",
    ],
  },

{
    name: "Daniel",
    image: "https://cms-imgp.jw-cdn.org/img/p/500100125/univ/art/500100125_univ_lsr_lg.jpg",
    hints: [
      "Minha sabedoria foi comparada à de um anjo pelo rei.",
      "Recebi visões proféticas sobre reinos futuros, incluindo um com dez chifres.",
      "Interpretei um sonho de Nabucodonosor sobre uma grande árvore.",
      "Meu livro menciona um período de 70 semanas proféticas.",
      "Pedi a meus amigos que orassem quando um rei exigiu que interpretasse um sonho sem contar qual era o sonho.",
      "Um rei pagão me chamou pelo nome de um de seus deuses: Beltessazar.",
      "Fui lançado em uma cova cheia de leões, mas saí ileso.",
      "Eu tinha três amigos chamados Sadraque, Mesaque e Abednego.",
      "Recusei comer os alimentos do rei.",
    ],
  },
  {
    name: "Ana",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102013252/univ/art/1102013252_univ_lsr_lg.jpg",
    hints: [
      "Meu cântico profético menciona um rei antes mesmo de Israel ter um.",
      "Eu e minha família fazíamos uma viagem anual a Silo.",
      "Meu cântico inspirou um dos cânticos mais famosos do Novo Testamento.",
      "Prometi que, se Deus me desse um filho, ele seria dedicado a Ele por toda a vida.",
      "Meu filho foi um dos maiores profetas de Israel.",
      "Fiz uma oração silenciosa no templo, o que levou o sacerdote a pensar que eu estava embriagada.",
      "Meu marido tinha outra esposa, que frequentemente me provocava.",
      "Meu filho ouviu a voz de Deus quando ainda era criança.",
      "Sou mãe de Samuel.",
    ],
  },

{
    name: "Gideão",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102016044/univ/art/1102016044_univ_lsr_lg.jpg",
    hints: [
      "Fiz um ídolo de ouro que se tornou um laço para meu povo.",
      "Construí um altar chamado 'Jeová-Shalom'.",
      "Tive de escolher meus guerreiros a partir da forma que bebiam a água do rio.",
      "Recusei a oferta de me tornar rei de Israel.",
      "Pedi um sinal de Deus usando um velo de lã.",
      "Destruí um altar de Baal, e por isso fui chamado de Jerubaal.",
      "Fui chamado de 'homem valente' por um anjo, mesmo me considerando fraco.",
      "Deus reduziu meu exército de milhares para apenas 300 soldados.",
      "Fui um dos juízes de Israel.",
    ],
  },

{
    name: "Timóteo",
    image: "https://cms-imgp.jw-cdn.org/img/p/2015809/univ/art/2015809_univ_lsr_lg.jpg",
    hints: [
      "Tive um problema de saúde que Paulo sugeriu tratar com um pouco de vinho.",
      "Meu nome significa 'aquele que honra a Deus'.",
      "Fui deixado para liderar a congregação de Éfeso.",
      "Fui um dos companheiros mais próximos do apóstolo Paulo.",
      "Apesar de jovem, recebi grandes responsabilidades.",
      "Minha mãe era judia, mas meu pai era grego.",
      "Desde a infância fui ensinado nas Escrituras.",
      "Fui circuncidado por Paulo para evitar obstáculos ao meu ministério.",
      "Recebi duas cartas de Paulo com conselhos sobre liderança.",
    ],
  },

{
    name: "Jeremias",
    image: "https://cms-imgp.jw-cdn.org/img/p/1102016067/univ/art/1102016067_univ_lsr_lg.jpg",
    hints: [
      "Fui proibido por Deus de me casar ou ter filhos.",
      "Testemunhei a destruição do Templo de Salomão.",
      "Fui chamado por Deus antes mesmo de nascer.",
      "Fiz um jugo de madeira para simbolizar a escravidão de Israel.",
      "Adverti repetidamente os reis de Judá, mas fui ignorado.",
      "Me tornei profeta ainda jovem.",
      "Escrevi um livro de lamentações sobre a queda de Jerusalém.",
      "Fui lançado em uma cisterna lamacenta e deixado para morrer.",
      "Fui um dos principais profetas de Judá antes do exílio babilônico.",
    ],
  },

];